### ISSUE TITLE
QR Code scan is taking too much time....

### ISSUE THREAD

**Issue by gvyas** [uport-project/uport-mobile-issues#12]
### Prerequisites
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
Using Lenovo Note 4 (A7010), 
Mediatek MT67853 processor, 3GB RAM
----
## Current Behavior
QR code scanning is too long to recognize 

## Expected Behavior
On one of my colleagues SONY xperia (snapdragon  430) phone is works like charm. 

### Steps to Reproduce
QR Scan with Mediatek processor may be an issue.

### Environment Details
* App Version: Latest
* Mobile OS Version: Android 6 (5th dec 2016 patch)
* Device details: lenov0 a7010a48

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by flaneuring** [comment]
Unable to repro on Android or iOS.
