### ISSUE TITLE
Push notification not received

### ISSUE THREAD

**Issue by twhay** [uport-project/uport-mobile-issues#16]
## Current Behavior
A user was issued an attestation when their uPort app was closed and they did not receive a notification that an attestation was issued to them, nor did they receive the attestation.

## Expected Behavior
When an attestation is issued it should appear as a notification within the uPort app, and a user should be able to accept the attestation within their uPort app and have it appear within their Verifications

## Failure Information (for bugs)
Getting this information, this bug was filed by one of our Beta testers and we are following up with the specific details. Will edit this issue once we have the information.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Certificate is issued after a student registers for it
2. Student's uPort application on their phone is closed, and they do not received the notification
3. Certificate is not received by the student.

### Environment Details
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* App Version: 10000309
* Mobile OS Version: Android 8.0.0
* Device details:

### Failure Logs/Screenshots
Please include any relevant log snippets or files here.

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by mirceanis** [comment]
This is tracked in https://github.com/uport-project/uport-mobile/issues/190
Closing this one
