### ISSUE TITLE
Enhancement Request: Do not allow QR code scanner to open until identity has been created

### ISSUE THREAD

**Issue by twhay** [uport-project/uport-mobile-issues#19]
## Current Behavior
In our beta tests, we have seen some users download uPort and then instantly try to interact with our application. Due to their identity being established, it takes on the order of minutes before then can interact with our application. They think the app is broken as there is nothing to tell them to not use the uPort application until all on chain information has been written.

## Expected Behavior
I would suggest either disabling the QR code scanner in the app until it can be successfully used to interact with an application (about 7 to 10 minutes after creating the identity) OR showing some text that says "Please wait while your identity is established" or "Wait: Transaction Writing to the Blockchain" so they don't try to interact with an app until that goes away.

## Failure Information (for bugs)
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Download the uPort app
2. Create an identity
3. As soon as the app is downloaded, try to use it to interact with an application. It will be typically 7 to 10 minutes before this can be done, due to the information that is being written on chain.

### Environment Details
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* App Version: All
* Mobile OS Version: All
* Device details: Any device

### Failure Logs/Screenshots
Please include any relevant log snippets or files here.

**Comment by KamesCG** [comment]
@twhay That's great feedback! Thank you submitting the issue.

I'll be sure to add the issue description add it to our internal issue tracker for potential enhancements.

**Comment by pelle** [comment]
This should be fixed in the next release. Thanks.
