### ISSUE TITLE
Test issue #2 -- uPort too awesome

### ISSUE THREAD

**Issue by bdresser** [uport-project/uport-mobile-issues#2]
# Current Behavior

uport is way too cool for me to handle

# Expected Behavior

i expect it to be like a avg mobile app but no

# Failure Information (for bugs)

hard to say, just can't deal idk 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

lol @ese ^

## Environment Details

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* App Version:
* Mobile OS Version:
* Device details:

## Failure Logs/Screenshots

Please include any relevant log snippets or files here.

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by Eseoghene** [comment]
This issue has been fixed and should be available in the next version of the app

**Comment by Eseoghene** [comment]
This issue has been fixed and should be available in the next version of the app
