### ISSUE TITLE
Don't allow saving a claim if incorrect sub is set

### ISSUE THREAD

**Issue by KamesCG** [uport-project/uport-mobile-issues#20]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

----

## Current Behavior
What is the current behavior?
Currently if I don't set my personal `address` as the subject `sub` claim when creating an attestation and I approve the request, the attestation doesn't appear in my verifications menu.

## Expected Behavior
Please describe the behavior you are expecting
As a User I want to see all the attestations/verifications I approve. If it's not standard to display an attestation with a different sub I shouldn't be allowed to approve the transaction. If the behavior is allowed then I want a separate window or search filter to view my verifications.

## Failure Information (for bugs)
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Generate Attestation with incorrect address. For example with `0x` prefixed
2. Approve Attestation
3. Can't find verification on uPort Mobile App.

**Comment by bdresser** [comment]
hi @KamesCG!! as noted in the [specs](https://github.com/uport-project/specs/blob/develop/messages/verification.md#attributes), `sub` is a required field in a verifiable claim. as a developer, you shouldn't be issuing credentials without using the proper `sub` field for the recipient.

you're right though that the mobile app shouldn't allow the user to save a credential not specified for them. going to update the issue title accordingly if that's okay :)

**Comment by KamesCG** [comment]
@bdresser you right...

it's the wild west out here and I'm just a code slinging cowboy - i need safety nets :)
