### ISSUE TITLE
Account recovery lookup failing

### ISSUE THREAD

**Issue by ryanmilvenan** [uport-project/uport-mobile-issues#21]
Please answer the following questions for yourself before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

----

## Current Behavior
On app version 318, when I try to recover my account using my 12-word seed phrase, I receive message saying 'Unable to lookup identity address'

## Expected Behavior
My account should be recovered

## Failure Information (for bugs)
I have no other information besides the error message

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Delete the uPort app.
2. Reinstall the uPort app.
3. Select 'Recover Identity'
4. Input 12 word seed phrase
5. Click Next
6. Error is shown

### Environment Details

App Version: 318(production)
Mobile OS Version: iOS 11.3
Device Details: iPhone X

### Failure Logs/Screenshots

![unable_error](https://user-images.githubusercontent.com/3486524/39076900-74a0935e-44bb-11e8-98b9-d697c0c87e67.jpeg)

**Comment by Eseoghene** [comment]
Hello @ryanmilvenan did you set your seed phrase successfully before deleting the uPort App?

**Comment by ryanmilvenan** [comment]
It’s been quite awhile since I installed the app originally, but I have had the phrase stored in my notes, so I believe so, yes.

**Comment by ryanmilvenan** [comment]
Also, in lieu of restoring my old identity, if I attempt to create a new one instead, everything seems to work as expected, until I try to scan a QR code, and I receive another error message saying, 'Identity registration transaction failed'
