### ISSUE TITLE
Insufficient funds when sending transaction with a keypair account

### ISSUE THREAD

**Issue by oed** [uport-project/uport-mobile-issues#23]
## Current Behavior
I get an "insuficient funds for gas" error when trying to send a transaction from a keypair account on rinkeby. When trying to view the account in the app the app crashes.

## Expected Behavior
The transaction should be sucessfully sent. Viewing the app specific account should not crash the app.

## Failure Information (for bugs)
I have 2 rinkeby ETH in the account that should send the tx, so there should be more than enough to pay for the gas.
This is the transaction I'm sending using `uport.sendTransaction` of uport-connect:
```js
{ nonce: 0,
     gasPrice: 90000000000,
     to: '0x37c3719cdabd54e6b5195e366f9ef8fc59a509e3',
     data: '0x8ac2571f0000000000000000000000004717a02d2730f4058540c420220629325f6245b56d75506f7274446f63756d656e74495046533132323000000000000000000000cf35bb754e4c4818a78bdd91b299da06d6e919cbbeef701fa68cbb1abd97e0cb',
     gasLimit: 52890 }
```

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. create a keypair account on rinkeby
2. send some ether to it
3. try sending a transaction from it

### Environment Details
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* App Version: 326 (alpha)
* Mobile OS Version: ios 11.3.1
* Device details: iphone 6

### Failure Logs/Screenshots
https://vimeo.com/270339868

**Comment by aldigjo** [comment]
@oed I can't seem to recreate this, could you provide the exact steps you did when encountering this? I tried by altering ticket-demo to create a keypair account. I sent some ETH to it, and was able to sign/send tx's from ticket-demo successfully.
