### ISSUE TITLE
Allow some slack for off-sync clocks when issuing JWTs

### ISSUE THREAD

**Issue by mirceanis** [uport-project/uport-mobile-issues#28]
@haraldrudell commented on [Wed Jul 04 2018](https://github.com/uport-project/uport-android/issues/3)

Android time synchronization is a bit lacking still in 8+

SYMPTOM
This causes the uPort Android client 10000338 to issue **problem syncing 401 - Invalid token** in ☰ - Advanced - System Messages and basically nothing network-related works

CAUSE
However, if one tries to login using qrcode here: https://appmanager.uport.me/
It says: JWT not valid yet (issued in the future): iat: 1530732693 > now: 1530732563.449
revealing what the problem is. My device time was 2 minutes ahead of true time

FIX
One could add an ntp client that would tell you how bad your clock is, or have a better error message

**Comment by mirceanis** [comment]
Issues like this can appear on multiple occasions and not just on android.

A possible fix is to add a couple minutes buffer interval when emitting JWTs or when verifying so that checks like this become a bit more lenient.

**Comment by mirceanis** [comment]
Linked issue in uport-connect: https://github.com/uport-project/uport-connect/issues/151

**Comment by mirceanis** [comment]
yes, I think that should be increased. is this the only js lib that verifies uport JWTs?
behavior should be made uniform

**Comment by rmw2** [comment]
I think it's also in [did-jwt/JWT.js:22](https://github.com/uport-project/did-jwt/blob/develop/src/JWT.js), and I'm not sure if anywhere else

**Comment by pelle** [comment]
@aldigjo can you create a companion PR in mobile bringing this in please
