### ISSUE TITLE
After recovery, user looks brand new on ethr-did internal versions

### ISSUE THREAD

**Issue by mirceanis** [uport-project/uport-mobile-issues#33]
## Current Behavior
Recovery seems to work in terms of account(device address is recovered correctly) but no actual user data is recovered.

## Expected Behavior
User is recovered along with any previous data (name, attestations, contacts, dApp interactions)

### Steps to Reproduce

1. Install a recent version (ex: v355)
2. Go through recovery. (either old seed or new seed phrase, doesn't matter)
3. recovered user always looks like a new user. :(

### Environment Details

* App Version:  v355 (but also present on previous internal versions, definitely > v338 since that one doesn't have ethrdid)
* Mobile OS Version: Android (but probably also on iOS)

**Comment by pelle** [comment]
@mirceanis Did the user have backup turned on?

**Comment by mirceanis** [comment]
@pelle yes. I first noticed the issue using a phrase that had been created in an older version.
Recovering using the same seed phrase in an older version (ex v338) works as expected.

**Comment by pelle** [comment]
@mirceanis It is probably a pre HD wallet user unfortunately. We need some UX to warn them. I'm moving this to next sprint, while we think of a solution.

**Comment by mirceanis** [comment]
@pelle I get the same behavior with pre-ethr-did and post-ethr-did recovery phrases.

ALSO, there seems to be a way to trigger a manual recovery by going into More > Advanced > Identity Hub Status and tapping on Devices Latest Hash.

For a post-ethr-did phrase, that does the trick and the user data gets recovered.
For a pre-ethr-did phrase, it only recovers partially.

**Comment by Eseoghene** [comment]
This is a valid issue and seems to happen when caleuche is returning errors

Using thia manual recovery by going into More > Advanced > Identity Hub Status and tapping on Devices Latest Hash also does not work, and returns the error events.slice is not a function 
See attached screenshots![IMG_0460.jpg](https://images.zenhubusercontent.com/5b3a5467fc589b1d091c3dfc/8f00c731-10c3-418f-beff-889e38d44f2e)![IMG_0461.jpg](https://images.zenhubusercontent.com/5b3a5467fc589b1d091c3dfc/101d6c81-8647-4aae-85f5-9badaa768c85)

**Comment by simonas-notcat** [comment]
https://github.com/ConsenSys/uport-mobile/pull/948
