### ISSUE TITLE
On ethr-did versions, buying shares on demo.uport.space does not trigger a notification in the app

### ISSUE THREAD

**Issue by mirceanis** [uport-project/uport-mobile-issues#34]
## Current Behavior
Buy shares on demo.uport.space does not trigger a notification in the app

## Expected Behavior
Buying shares should trigger a notification in the app.

## Failure Information (for bugs)
I see `error in handleEncryptedMessage()` in the logs

### Steps to Reproduce
* Install a recent version that has ethrdid (ex v355)
* login to demo.uport.space on desktop
* attempt to buy shares
* no notification appears in the app

### Environment Details
* App Version: v355
* Mobile OS Version: Android (but not necessarily android specific)

**Comment by pelle** [comment]
I was able to recreate this. Lets see if this is an issue in Pututu or libraries
