### ISSUE TITLE
Incorrectly formatted hash params returned 

### ISSUE THREAD

**Issue by zachferland** [uport-project/uport-mobile-issues#36]
## Current Behavior
Mobile flows not working since hash params are returned incorrectly as `#&access_token=...`. generally uport-connect does not expect to parse incorrectly formed hash params

## Expected Behavior
Callback response should be parsed and returned as normally. This occurs when hash params correctly formed as `#access_token=...`

### Steps to Reproduce
1. visit demo.uport.me
2. click connect
3. accept req in app
4. return to demo.uport.me by mobile app but notice nothing happened and you can the url it tried to open 

### Environment Details

* App Version: 355
* Mobile OS Version: IOS
* Device details: iPhone x

**Comment by pelle** [comment]
@zachferland what is incorrect about the hash param? It should be able to handle a & prefix.

```js
> qs.parse('access_token=dddd')
{ access_token: 'dddd' }
> qs.parse('&access_token=dddd')
{ access_token: 'dddd' }
```

**Comment by zachferland** [comment]
@pelle I can follow up/confirm today, yeah technically the libs can handle it, but if we wanted them properly formed, `&` would only be a delimiter between args

**Comment by Eseoghene** [comment]
1

**Comment by zachferland** [comment]
This can be recreated at demo.uport.space now, only happens when additional hash params are parsed through and returned. Need to also check if the id param is even getting passed through

**Comment by zachferland** [comment]
Not entirely sure that it not some handlers in the library modifying it, but need some mobile help to debug/pinpoint anyways

**Comment by zachferland** [comment]
After further investigation, this was a combination of two issues, 1 in both libs and mobile 

Lib - Request id was not passed in new requests as hash params, so it would not return a response 

Resolved by - https://github.com/uport-project/uport-connect/pull/181

Mobile - if mobile was given a redirect callback with a `#` it assumed hash params existed and returned `#&param=param`, even though no hash params were passed, minor case which will not come up often, if at all, but should still support properly
