### ISSUE TITLE
404 on Support Link

### ISSUE THREAD

**Issue by JDFind** [uport-project/uport-mobile-issues#43]
## Current Behavior
Taping Support in About opens the `support.uport.me` webpage which displays a 404 error. 

## Expected Behavior
Support button should redirect to a valid webpage.

As an improvement, I would suggest using Firebase Remote Config to dynamically update this kind of links "on the fly".

### Steps to Reproduce
1. open uPort while having an identity created or recovered
2. go to About
3. tap Support

### Environment Details
* App Version: 1.5.338
* Mobile OS Version: Android 8.0

**Comment by flaneuring** [comment]
Unable to reproduce on iOS and Android.
