### ISSUE TITLE
Mobile app not handling push responses 

### ISSUE THREAD

**Issue by zachferland** [uport-project/uport-mobile-issues#46]
On testflight release with major libs. The phone receives it, but it is not opened in app, we have seen a very similar error in the past. This could very well be the libs since a lot of that push code is newer, none the less without any error output in the app, i need help debugging and pin pointing the problem

**Comment by Eseoghene** [comment]
3

**Comment by zachferland** [comment]
@aldigjo said it just seems to be mobile not using the correct handler for unified request urls

**Comment by pelle** [comment]
The problem is in uport-transports. I'm replacing this with a new story there.

**Comment by pelle** [comment]
Replaced by https://github.com/uport-project/uport-transports/issues/9
