### ISSUE TITLE
Mobile Flow: Mobile Request Opens, but then does not redirect to back to browser, just closes card and remains in uport app.

### ISSUE THREAD

**Issue by zachferland** [uport-project/uport-mobile-issues#47]
This is with major libs at demo.uport.space, this is potentially a library issue, will add comment here once determined where the error likely is (lib or mobile)

**Comment by zachferland** [comment]
Update: this is both mobile app and library bug

Library - The library should be explicit as it can about callback params, in this case it should add the callback_type=redirect to the request

Mobile - When no callback_type (and/or redirect_url) it should make a best effort guess (just as it has done in the past. It this is case the fallback should have been redirect given how the request was received.

**Comment by zachferland** [comment]
https://github.com/uport-project/uport-connect/pull/177

**Comment by Eseoghene** [comment]
Cannot test this as the app keeps crashing when a transaction is sent for signing @zachferland @aldigjo
