### ISSUE TITLE
Double transaction cards displayed when pushed from mobile browser

### ISSUE THREAD

**Issue by bdresser** [uport-project/uport-mobile-issues#5]
# Current Behavior
App Launches with two transaction card opened, and notification count of 2 on home screen

# Expected Behavior
App Launches with one transaction card opened, and notification count of 1 on home screen

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Reset Identity
2. Create Identity ensuring you Tap on ' turn on notifications during onboarding
3. Launch demo.uport.me on mobile browser
4. Login
5. Buy Shares

## Environment Details

iOS 11 v304

* App Version: 304
* Mobile OS Version: 11
* Device details: iPhone X

## Failure Logs/Screenshots

Please include any relevant log snippets or files here.

[ScreenRecording_01-12-2018 19-54-45.m4v.zip](https://github.com/uport-project/uport-mobile-issues/files/1657847/ScreenRecording_01-12-2018.19-54-45.m4v.zip)

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly
