### ISSUE TITLE
Mobile app crashes on Eth Transfer transaction

### ISSUE THREAD

**Issue by rmw2** [uport-project/uport-mobile-issues#53]
Using the UportSubprovider with web3 1.0, making an Eth transfer crashes in the mobile app

To reproduce:
```javascript
connect = new Connect('TestApp')
web3 = new Web3(connect.getProvider())

// this crashes in the mobile app
web3.eth.sendTransaction({value: someValue, to: someAddress, from: ignoredAddress}, (err, txHash) => {
  // never gets here
})
```

I'm not sure if this is anything different with web3 1.0, or if this was the case in old web3 as well.  Simonas said he ran into a similar crash on Eth transfers.

**Comment by simonas-notcat** [comment]
https://github.com/ConsenSys/uport-mobile/pull/943
