### ISSUE TITLE
Adding photo crashes app on Pixel XL

### ISSUE THREAD

**Issue by AlbertoElias** [uport-project/uport-mobile-issues#6]
# Current Behavior

Clicking upload photo, doesn't matter if you pick Camera or Gallery, the app crashes
# Expected Behavior

Being able to change my profile photo

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Go to My Information
2. Edit
3. Tap to add photo
4. Select either option

(Also happens when setting up uPort for the first time)

## Environment Details

* App Version: 10000297
* Mobile OS Version: 8.1
* Device details: Pixel XL

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly
