### ISSUE TITLE
Attestation is not being received by identity created with app version 371

### ISSUE THREAD

**Issue by twhay** [uport-project/uport-mobile-issues#60]
----

## Current Behavior
What is the current behavior?
After scanning the QR code created by an app - the Ethense App, no push notification is received by the user.
## Expected Behavior
Please describe the behavior you are expecting
The user typically receives a push notification from the Ethense app to their uPort.
## Failure Information (for bugs)
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Receive QR code via email from Ethense
2. Scan QR code with uPort app (also have an embedded link to share information)
3. Information is shared and push is initiated by the application, but does not reach the uPort application of the user

### Environment Details
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* App Version: 271
* Mobile OS Version: IOS 11.4
* Device details: iPhone 7

### Failure Logs/Screenshots
Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/5604190/46317129-20c4ae80-c5a0-11e8-9abd-fe9c00113220.png)

**Comment by mi-xu** [comment]
This is most likely due to the fact that the latest version of the mobile app requires updating the `uport-js` (now renamed `uport-credentials`) library in order to maintain compatibility. I will coordinate with @twhay and support them on performing the upgrade.
