### ISSUE TITLE
QR scanner is unresponsive after sending the app to the background and opening again

### ISSUE THREAD

**Issue by malithrw** [uport-project/uport-mobile-issues#63]
## Current Behavior
When opening the app that is on the background, the QR scanner is unresponsive. Even if you exit from the QR scanner and go back it does not work. 

Need to kill the app and open again to make it to work again.

## Expected Behavior
QR scanner should be working after opening the app from the background.

### Steps to Reproduce

1. Open the app.
2. Open the QR scanner.
3. Send the app to the background by pressing home.
4. Re-open the app and try the QR scanner.

### Environment Details

* App Version: 430
* Mobile OS Version: iOS 12.2
* Device details: Apple iPhone 7

### Failure Logs/Screenshots

[Video](https://photos.google.com/share/AF1QipOwqA8IwcfygVxBsxODdIhI-E9bqOQnou7PulwaekbTfv7Z6x560dk__zIHEdvBpg/photo/AF1QipPIghqyf92YkBMFywW_ITREyHx7CtnYGKZ8xx9G?key=elRIeEZYV3hMZ3R0VDV6a0d0Mi1sZ2VoaExhUE1n) of recreating the bug.

**Comment by jasonhealy** [comment]
@malithrw Thanks for reporting. This will be fixed in next release v1.6.2 expected this week.

**Comment by malithrw** [comment]
@jasonhealy That's great news! Thank you.
