### ISSUE TITLE
Information input fields aren't visible

### ISSUE THREAD

**Issue by AlbertoElias** [uport-project/uport-mobile-issues#7]
# Current Behavior

I can't see what I'm typing in the different input fields when editing my information

# Expected Behavior

Being able to see the input fields

# Failure Information (for bugs)

Tapping in the middle seems to activate the keyboard, and you can see like a pixel at the top of the field

## Steps to Reproduce

1. Go to My Information
2. Edit

(Also happens when setting up uPort for the first time)

## Environment Details

* App Version: 10000297
* Mobile OS Version: 8.1/7.0
* Device details: Pixel XL/Galaxy S7

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by KamesCG** [comment]
I've tested uPort on several Android devices and can confirm this happens on both cheaper and medium priced Android devices: Kyocera and Stylus 2.
