### ISSUE TITLE
Contact request notification card mis-sized & unable to scroll

### ISSUE THREAD

**Issue by Detoo** [uport-project/uport-mobile-issues#8]
# Current Behavior

Contact request notification card takes excessive vertical space and I was unable to scroll to the bottom of the modal. (as shown in the screenshot)
# Expected Behavior

Notification card should be reasonably sized and the modal should be scrollable.

# Failure Information (for bugs)

Content height calculation seems off. The avatar should be a circle but instead becomes excessively high and the scrollable region does not fit the card height.

## Steps to Reproduce

1. Take a contact request on UportMobile (ex. [https://id.uport.me/0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef](https://id.uport.me/0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef))
2. When the request modal shows up in app, tap "x" to dismiss it
3. Tap the notification button to open the notification modal

## Environment Details

* App Version: 297(production)
* Mobile OS Version: iOS 11.2.5
* Device details: iPhone X

## Failure Logs/Screenshots

![img_6167](https://user-images.githubusercontent.com/1946265/35375524-2ffce510-015c-11e8-9523-397e7bd2a120.PNG)

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by ShaydeNofziger** [comment]
Is this a complex claim, per-chance? If so, this issue may be related to #10

**Comment by Detoo** [comment]
No it’s just a contact request. There is an example of making such request in step 1.
