### ISSUE TITLE
App crashes after pushing "Accept" button

### ISSUE THREAD

**Issue by pjholmes** [uport-project/uport-mobile-issues#9]
## What is the current behavior?
The application terminates unexpectedly.

## Expected Behavior
The application should continue to run.

## Failure Information (for bugs)
I installed the app, started it, clicked "Create Identity", clicked "Accept", and the app terminates. Tried it several times.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Start the app
2. Click "Create Identity"
3. Click "Accept"
4. The app terminates, 

### Environment Details
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* App Version: 1.5.8
* Mobile OS Version: 11.2.2 (15C202)
* Device details: iPhone X (MQAU2LL/A)

### Failure Logs/Screenshots
Please include any relevant log snippets or files here.

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by pjholmes** [comment]
I upgraded to iOS 11.2.5 (15D60) and found the same behavior.

**Comment by bdresser** [comment]
@pjholmes could you upgrade to uPort 1.5.9 and let us know if the issue persists?

**Comment by bdresser** [comment]
@pjholmes we believe this issue is fixed on 1.5.9 and beyond - please try downloading uPort 318 from the app store and let us know if you're still encountering the issue! if not, will close
